@echo off 
echo "jup		-->	Changes directory and opens Jupyter Lab in work directory"
echo "i		-->	Sets Proxy(GITAM)"
echo "o		-->	Resets Proxy to None"
echo "chr		-->	Opens Chrome"
echo "pull		-->	Pulls the working repo"
echo "push		-->	Adds, Commits, and Pushes working repo"
echo "l		-->	Linux Implimentation[Beta]"
echo "desktop	--> 	Change Directory to Desktop"
echo "kri		-->	Login into Krishna"
echo "m		-->	Executes main.py file in directory"
echo "n		-->	Executes <file-name> variable file. Set the variable with <set file-name=[filename.py]"